language: java
jdk:
  - oraclejdk8
install: true
script: mvn clean install -B -V
after_success:
  - mvn jacoco:report && bash <(curl -s https://codecov.io/bash) || echo "Codecov did
    not collect coverage reports"
cache:
  directories:
    - "$HOME/.m2"
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - openssl aes-256-cbc -K $encrypted_c73894d72094_key -iv $encrypted_c73894d72094_iv
    -in sonatype.pgp.enc -out sonatype.pgp -d
