language: java
jdk:
  - oraclejdk8
install: mvn --settings .maven.xml clean install -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
after_success:
  - mvn --settings .maven.xml clean deploy -DskipTests=true -B -U -Prelease
  - mvn --settings .maven.xml jacoco:report && bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

cache:
  directories:
    - "$HOME/.m2"
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
